//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABOCUOTA
    {
        public string ABO_NUMFAC { get; set; }
        public string ABO_NUMCUO { get; set; }
        public string ABO_NUMABO { get; set; }
        public Nullable<decimal> ABO_MONTOT { get; set; }
        public Nullable<decimal> ABO_MONTOC { get; set; }
        public Nullable<decimal> ABO_MONTOI { get; set; }
        public string ABO_FECHA { get; set; }
        public int Id { get; set; }
    }
}
