//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABOOCARG
    {
        public string ABO_NUMFIN { get; set; }
        public string ABO_SECCAR { get; set; }
        public string ABO_NUMABO { get; set; }
        public string ABO_CODCAR { get; set; }
        public string ABO_MONTOT { get; set; }
        public string ABO_FECHA { get; set; }
        public int ID { get; set; }
    }
}
