//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivos_subir
    {
        public string nombreArchivo { get; set; }
        public string nombreTabla { get; set; }
        public Nullable<bool> subir { get; set; }
        public int ID { get; set; }
    }
}
