//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANCO
    {
        public int BCO_CODIGO { get; set; }
        public string BCO_NOMBRE { get; set; }
        public string BCO_ABREVI { get; set; }
        public string BCO_SUCURS { get; set; }
        public string BCO_TELEF1 { get; set; }
        public string BCO_TELEF2 { get; set; }
        public string BCO_TELEF3 { get; set; }
    }
}
