//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTERA
    {
        public Nullable<double> CAR_MONTOC { get; set; }
        public Nullable<double> CAR_MONTOI { get; set; }
        public Nullable<double> CAR_OTRCAR { get; set; }
        public Nullable<double> CAR_DEDUCC { get; set; }
        public Nullable<double> CAR_CAPPER { get; set; }
        public Nullable<double> CAR_INTPER { get; set; }
        public int ID { get; set; }
    }
}
