//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTABANCO
    {
        public int CTA_CODIGO { get; set; }
        public string CTA_BANCO { get; set; }
        public string CTA_NUMERO { get; set; }
        public string CTA_BALFEC { get; set; }
        public string CTA_BALCOR { get; set; }
        public Nullable<System.DateTime> CTA_FECCOR { get; set; }
    }
}
