//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUOTA
    {
        public int CUO_NUMFAC { get; set; }
        public int CUO_NUMCUO { get; set; }
        public int CUO_NUMREC { get; set; }
        public string CUO_STATUS { get; set; }
        public Nullable<double> CUO_MONTOT { get; set; }
        public Nullable<double> CUO_MONTOC { get; set; }
        public Nullable<double> CUO_MONTOI { get; set; }
        public string CUO_FECHAV { get; set; }
        public string CUO_FECHAP { get; set; }
        public string CUO_TIPO { get; set; }
        public string CUO_STAANT { get; set; }
        public int ID { get; set; }
    }
}
