//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTDCTA
    {
        public Nullable<int> EST_NUMFIN { get; set; }
        public Nullable<double> EST_BALINI { get; set; }
        public Nullable<double> EST_CAPINI { get; set; }
        public Nullable<double> EST_INTINI { get; set; }
        public Nullable<double> EST_OTRCAR { get; set; }
        public Nullable<double> EST_BALACT { get; set; }
        public Nullable<double> EST_CAPPAG { get; set; }
        public Nullable<double> EST_INTPAG { get; set; }
        public Nullable<double> EST_CARRYP { get; set; }
        public Nullable<double> EST_CARNRP { get; set; }
        public Nullable<double> EST_CAPPER { get; set; }
        public Nullable<double> EST_INTPER { get; set; }
        public string EST_STATUS { get; set; }
        public int ID { get; set; }
    }
}
