//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA()
        {
            this.FINANCY = new HashSet<FINANCY>();
        }
    
        public int FAC_NUMERO { get; set; }
        public Nullable<int> FAC_NUMFIN { get; set; }
        public Nullable<int> FAC_TIPINT { get; set; }
        public Nullable<int> FAC_FORMPG { get; set; }
        public Nullable<int> FAC_TIPFIN { get; set; }
        public Nullable<double> FAC_MONTO { get; set; }
        public string FAC_FECHA { get; set; }
        public Nullable<int> FAC_NUMCUO { get; set; }
        public Nullable<double> FAC_INTERE { get; set; }
        public string FAC_GARANT { get; set; }
        public string FAC_STATUS { get; set; }
    
        public virtual FORMAPG FORMAPG { get; set; }
        public virtual TIPOFIN TIPOFIN { get; set; }
        public virtual TIPOINT TIPOINT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINANCY> FINANCY { get; set; }
    }
}
