//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIADOR()
        {
            this.FINANCY = new HashSet<FINANCY>();
        }
    
        public int FIA_CODIGO { get; set; }
        public string FIA_NOMBRE { get; set; }
        public string FIA_CEDULA { get; set; }
        public string FIA_TELEFO { get; set; }
        public string FIA_DIRECC { get; set; }
        public string FIA_CODCTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINANCY> FINANCY { get; set; }
    }
}
