//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCY
    {
        public int FIN_NUMERO { get; set; }
        public Nullable<int> FIN_NUMCTE { get; set; }
        public Nullable<int> FIN_NUMFAC { get; set; }
        public Nullable<int> FIN_NUMFIA { get; set; }
        public Nullable<int> FIN_NUMVEN { get; set; }
        public Nullable<int> FIN_STATUS { get; set; }
        public int ID { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FACTURA FACTURA { get; set; }
        public virtual FIADOR FIADOR { get; set; }
        public virtual VENDEDOR VENDEDOR { get; set; }
    }
}
