//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGCUOTA
    {
        public int ING_NUMREC { get; set; }
        public Nullable<int> ING_NUMFIN { get; set; }
        public string ING_STATUS { get; set; }
        public Nullable<decimal> ING_MONTOT { get; set; }
        public Nullable<decimal> ING_MONTOC { get; set; }
        public Nullable<decimal> ING_MONTOI { get; set; }
        public string ING_FECHA { get; set; }
        public string ING_FORMPG { get; set; }
        public string ING_DESCRI { get; set; }
        public string ING_NCF { get; set; }
        public int ID { get; set; }
    }
}
