//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTROCARG
    {
        public string CAR_NUMFIN { get; set; }
        public string CAR_SECU { get; set; }
        public string CAR_CODCAR { get; set; }
        public string CAR_NUMREC { get; set; }
        public string CAR_STATUS { get; set; }
        public string CAR_MONTOT { get; set; }
        public string CAR_FECHAR { get; set; }
        public string CAR_FECHAP { get; set; }
        public int id { get; set; }
    }
}
