//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTROSDB
    {
        public int ID { get; set; }
        public int BANCO { get; set; }
        public int CUENTA_BANCARIA { get; set; }
        public int TIPO_ENTRADA { get; set; }
        public int TIPO_DEBITO { get; set; }
        public decimal MONTO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string CONCEPTO { get; set; }
        public bool ACTIVO { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> NUM_FIN { get; set; }
        public Nullable<int> NUM_REC { get; set; }
    }
}
