//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTEMA
    {
        public string SIS_EMPRES { get; set; }
        public string SIS_DIRECC { get; set; }
        public string SIS_TELEFO { get; set; }
        public string SIS_RNC { get; set; }
        public string SIS_DEPART { get; set; }
        public string SIS_PASO { get; set; }
        public string SIS_SIGNAL { get; set; }
        public string SIS_ULTCHE { get; set; }
        public string SIS_ULTCLI { get; set; }
        public string SIS_ULTFIA { get; set; }
        public string SIS_ULTFIN { get; set; }
        public string SIS_ULTFAC { get; set; }
        public string SIS_ULTREC { get; set; }
        public string SIS_ULTVEN { get; set; }
        public string SIS_ULTDEP { get; set; }
        public string SIS_ULTCOM { get; set; }
        public string SIS_SENAL2 { get; set; }
        public string SIS_ULTSAL { get; set; }
        public string SIS_NCF1 { get; set; }
        public string SIS_NCF2 { get; set; }
        public System.DateTime FECHA_CIERRE { get; set; }
        public int ID { get; set; }
    }
}
