//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ConsultaFin
    {
        public int FAC_NUMFIN { get; set; }
        public string CUO_STATUS { get; set; }
        public double CUO_MONTOT { get; set; }
        public decimal CUO_MONTOI { get; set; }
        public decimal CUO_MONTOC { get; set; }
        public int CUO_NUMCUO { get; set; }
        public decimal BalanceTotal { get; set; }
        public string cliente { get; set; }
        public string FAC_FECHA { get; set; }
    }
}
