//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ConciliacionBancaria
    {
        public int ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public string FECHATXT { get; set; }
        public string TRANSACION { get; set; }
        public string CUENTA { get; set; }
        public string CONCEPTO { get; set; }
        public decimal DEBITO { get; set; }
        public decimal CREDITO { get; set; }
        public bool VALIDADO { get; set; }
        public decimal BALANCECORTE { get; set; }
        public string TIPO { get; set; }
        public bool CERRADO { get; set; }
    }
}
