//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CuadreCajaSalidas
    {
        public int ID { get; set; }
        public string Cliente { get; set; }
        public string Recibo { get; set; }
        public string Descripcion { get; set; }
        public decimal MontoTotal { get; set; }
        public int MontoCapital { get; set; }
        public int MontoInteres { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string FechaTexto { get; set; }
        public string Tipo { get; set; }
        public string TextoTipo { get; set; }
        public int keyId { get; set; }
    }
}
