//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_rptRegistroNCF
    {
        public string ING_NUMREC { get; set; }
        public int ING_NUMFIN { get; set; }
        public string ING_STATUS { get; set; }
        public decimal ING_MONTOT { get; set; }
        public decimal ING_MONTOC { get; set; }
        public decimal ING_MONTOI { get; set; }
        public string ING_FECHA { get; set; }
        public string ING_FORMPG { get; set; }
        public string ING_DESCRI { get; set; }
        public string ING_NCF { get; set; }
        public string mes { get; set; }
        public string dia { get; set; }
        public string year { get; set; }
        public string mesAbr { get; set; }
        public decimal MORA { get; set; }
        public string Cliente { get; set; }
        public System.DateTime fechadt { get; set; }
        public int ClienteId { get; set; }
        public bool isCuadrada { get; set; }
    }
}
