//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_rptDebitosBancarios
    {
        public int ID { get; set; }
        public bool ACTIVO { get; set; }
        public string CONCEPTO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string FECHAtxt { get; set; }
        public string TIPO { get; set; }
        public string ENTRADA { get; set; }
        public decimal MONTO { get; set; }
        public string BANCO { get; set; }
        public string CUENTA { get; set; }
    }
}
