//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_rptCuotasVencidas
    {
        public int C__FIN { get; set; }
        public int CodigoCLiente { get; set; }
        public string CLIENTE { get; set; }
        public string CEDULA_CLIENTE { get; set; }
        public string DIRE_CLIENTE { get; set; }
        public string FIADOR { get; set; }
        public string TELEFONO_FIADOR { get; set; }
        public string Cedula_FIADOR { get; set; }
        public string PROMOTOR { get; set; }
        public string Fecha { get; set; }
        public string CUOTA { get; set; }
        public decimal MONTO { get; set; }
        public string TELEFONO { get; set; }
        public string TELEFONO2 { get; set; }
        public string DESCRIPCION { get; set; }
        public string FechaAbono { get; set; }
        public int NUM_CUOTA { get; set; }
        public string empresa { get; set; }
        public decimal CapitalTotal { get; set; }
        public decimal InteresTotal { get; set; }
        public double capitalAbono { get; set; }
        public double interesAbono { get; set; }
        public double capital { get; set; }
        public double INTERES { get; set; }
        public string CUO_STATUS { get; set; }
        public string FAC_GARANT { get; set; }
        public double FAC_INTERE { get; set; }
        public string Status { get; set; }
        public decimal mora { get; set; }
        public string CUO_TIPO { get; set; }
        public System.DateTime fechadt { get; set; }
    }
}
