//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_rptFinAtrasados
    {
        public int C__FIN { get; set; }
        public string CLIENTE { get; set; }
        public string CEDULA_CLIENTE { get; set; }
        public string DIRE_CLIENTE { get; set; }
        public string TELEFONO1 { get; set; }
        public string TELEFONO2 { get; set; }
        public string ULTIMO_PAGO { get; set; }
        public int CUOTA { get; set; }
        public string CuotaTxt { get; set; }
        public decimal MONTO { get; set; }
        public decimal CAPITAL { get; set; }
        public decimal INTERES { get; set; }
        public string empresa { get; set; }
        public string FIADOR { get; set; }
        public string TELEFONO_FIADOR { get; set; }
        public string CEDULA_FIADOR { get; set; }
        public string PROMOTOR { get; set; }
        public double BalanceCapitalTOTAL { get; set; }
        public double BalanceInteresTOTAL { get; set; }
        public double balanceTOTAL { get; set; }
        public double MontoTotal { get; set; }
        public string FAC_GARANT { get; set; }
        public double FAC_INTERE { get; set; }
        public int CodigoCLiente { get; set; }
        public System.DateTime fechadt { get; set; }
        public int CUOTA_PENDIENTE { get; set; }
        public int CUOTA_TOTAL { get; set; }
        public decimal mora { get; set; }
        public string forma_pago { get; set; }
        public string fecha { get; set; }
        public string dia { get; set; }
        public string mes { get; set; }
        public string year { get; set; }
    }
}
