//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaImbrino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_SearchClientes_Fiadores
    {
        public int CTE_CODIGO { get; set; }
        public string CTE_NOMBRE { get; set; }
        public string CTE_APELLI { get; set; }
        public string CTE_CEDULA { get; set; }
        public string CTE_TELEFO { get; set; }
        public string CTE_DIRECC { get; set; }
        public string Zona { get; set; }
        public string Tipo { get; set; }
        public int type { get; set; }
    }
}
